# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmk2_1RMYVz7oGDlofk8Et70u50ytcc2
"""

def bisiesto(year):
  a=year%4
  b=year%100
  c=year%400
  if (a==0 and b!=0) or (a==0 and c==0):
    bis=1
  else:
    bis=0
  return bis
  
def daysInMonth(year, month):
  x=bisiesto(year)
  if x==1 and month==2:
    res=29
    return res
  else:
    if month==1 or month==3 or month==5 or month==7 or month==8 or month==10 or month==12:
      res=31
      return res
    elif month==2:
      res=28
      return res
    else:
      res=30
      return res
 

testYears = [1900, 2000, 2016, 1987]
testMonths = [2, 2, 1, 11]
testResults = [28, 29, 31, 30]

for i in range(len(testYears)):
  yr = testYears[i]
  mo = testMonths[i]
  print(yr, mo, "->", end="")
  result = daysInMonth(yr, mo)
  if result == testResults[i]:
    print("OK")
  else:
    print("Failed")