# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmk2_1RMYVz7oGDlofk8Et70u50ytcc2
"""

def bisiesto(year):
  a=year%4
  b=year%100
  c=year%400
  if (a==0 and b!=0) or (a==0 and c==0):
    bis=1
  else:
    bis=0
  return bis
  
def daysInMonth(year, month):
  x=bisiesto(year)
  if x==1 and month==2:
    res=29
    return res
  else:
    if month==1 or month==3 or month==5 or month==7 or month==8 or month==10 or month==12:
      res=31
      return res
    elif month==2:
      res=28
      return res
    else:
      res=30
      return res

def dayOfYear(year, month, day):
  total=0
  if year>0 and (month>0 and month<13) and (day>0 and day<32):
    for i in range(month-1):
      meses=daysInMonth(year,i+1)
      total=total+meses
    total=total+day
    return total
  else:
    return None
  
print(dayOfYear(2000, 12, 31)) 
print(dayOfYear(2020, 2, 29))
print(dayOfYear(1986, 9, 23))