# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmk2_1RMYVz7oGDlofk8Et70u50ytcc2
"""

def bisiesto(year):
  a=year%4
  b=year%100
  c=year%400
  if (a==0 and b!=0) or (a==0 and c==0):
    bis=True
  else:
    bis=False

  print("El año es bisiesto: {}" .format(bis))

ano=int(input("Ingrese un año: "))
bisiesto(ano)