# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cmk2_1RMYVz7oGDlofk8Et70u50ytcc2
"""

name=input("Ingrese su nombre: ")
apellido=input("Ingrese su apellido: ")
ubic=input("Ingrese su ubicación: ")
edad=input("Ingrese su edad: ")
print("La estudiante {} {} tiene {} años y reside en {}" .format(name,apellido,edad,ubic))